In [1]:
import numpy as np
import matplotlib.pyplot as plt

1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [16]:
def calc_logloss(y, y_pred):
    not_zero = 10e-8
    err = - np.mean(y * np.log(y_pred + not_zero) + (1.0 - y) * np.log(1.0 - y_pred + not_zero))
    err = np.sum(err)
    return err

In [17]:
# Пример применения
y1 = np.array([1, 0, 0, 1])
y_pred1 = np.array([0.9, 0.1, 0, 1])
calc_logloss(y1, y_pred1)

0.052680152273363166


2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.


In [18]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [29]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
#         if i % (iterations / 10) == 0:
#             print(i, W, err)
    return W, err

In [20]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [21]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2,  1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [22]:
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])

In [23]:
X_st

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  2.        ,  5.        ,  3.        ,
         0.        ,  5.        , 10.        ,  1.        ,  2.        ],
       [-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
        -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735],
       [ 1.        ,  1.        ,  2.        ,  1.        ,  2.        ,
         1.        ,  3.        ,  3.        ,  1.        ,  2.        ]])

500 [ 0.47822106 -0.20918419  0.64605995  1.49531432] 1.0559629735766491
1000 [ 0.46074241 -0.27647603  0.64395686  1.46891696] 0.9452143163455625
1500 [ 0.44435675 -0.33951515  0.64152026  1.44406912] 0.8478356492175442
2000 [ 0.42913461 -0.39751872  0.63899625  1.42106251] 0.7651174792493958
2500 [ 0.41513888 -0.44956784  0.63671032  1.40023024] 0.6981290738656131
3000 [ 0.40240136 -0.49488241  0.63498247  1.38184975] 0.6468811499046306
3500 [ 0.39088925 -0.53321212  0.63401986  1.36601535] 0.6097019385521372
4000 [ 0.38049869 -0.56497213  0.63387116  1.35259671] 0.5836772045802464
4500 [ 0.37108342 -0.59102182  0.63446603  1.3413119 ] 0.5657145327483051
5000 [ 0.36249064 -0.61234585  0.63568321  1.33183158] 0.5532735774580366
[ 0.36249064 -0.61234585  0.63568321  1.33183158] 0.5532735774580366


In [57]:
iter_lst = [10000, 20000, 30000, 40000]
alpha_lst = [1e-2, 5e-2, 0.1, 0.5, 1]

In [58]:
min_err = np.inf
for i in iter_lst:
    for a in alpha_lst:
        W, err = eval_model(X_st, y, iterations=i, alpha=a)
        print (f'iterations = {i}, alpha = {a}:\n W = {W}, logloss = {err}')
        if err < min_err  and err > 0:
            min_err = err
            alpha_best = a
            iter_best = i
            W_best = W
            print ('!!!NEW minimum!!!\n')
print(f' Best params:\n iterations = {iter_best}, alpha = {alpha_best}, logloss = {min_err}\n\
        Weights = {W_best}')
    

iterations = 10000, alpha = 0.01:
 W = [-2.51838389 -0.94526222  0.40028955  3.13247255], logloss = 0.3753577564443368
!!!NEW minimum!!!

iterations = 10000, alpha = 0.05:
 W = [-7.45468424 -1.13933276 -1.38016277  6.55241323], logloss = 0.26980751218990945
!!!NEW minimum!!!

iterations = 10000, alpha = 0.1:
 W = [-10.744631    -1.38398009  -2.42084781   9.13416686], logloss = 0.2321440525133421
!!!NEW minimum!!!

iterations = 10000, alpha = 0.5:
 W = [-24.52791135  -2.59436019  -6.46612462  20.31385673], logloss = 0.1438791521396508
!!!NEW minimum!!!

iterations = 10000, alpha = 1:
 W = [-33.60724757  -3.41474448  -9.03744936  27.66630585], logloss = 0.11458801899682125
!!!NEW minimum!!!

iterations = 20000, alpha = 0.01:
 W = [-4.27621379 -0.98162746 -0.27399347  4.26180494], logloss = 0.32664857139933945
iterations = 20000, alpha = 0.05:
 W = [-10.744375    -1.38395948  -2.42076898   9.13396218], logloss = 0.2321438248673863
iterations = 20000, alpha = 0.1:
 W = [-15.4271433   -1.78

Вывод - чем больше alpha и iterations - тем меньше logloss (с риском переобучения)

3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).


In [55]:
def calc_pred_proba(W,X):
    return sigmoid(np.dot(W, X))

In [60]:
np.round(calc_pred_proba(W, X_st), 2)

array([0.31, 0.  , 1.  , 0.  , 0.98, 0.  , 1.  , 0.  , 0.71, 1.  ])

In [61]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).


In [62]:
def calc_pred(W,X):
    return np.round(sigmoid(np.dot(W, X)),0)

In [64]:
y_pred = calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.


$$accuracy(a,x) = \frac{1}{l} \sum^{l}_{i=1}[a(x_{i})=y_{i}].$$


In [71]:
def accuracy(y, y_pred):
    return np.sum(y == y_pred)/y.shape[0]

In [72]:
accuracy(y, y_pred)

1.0

In [75]:
y_pred_2 = np.array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])

In [76]:
accuracy(y, y_pred_2)

0.2

In [87]:
def c_matrix(y, y_pred):
    TP, TN, FP, FN = 0,0,0,0
    for i in range(y.shape[0]):
        if y[i] == y_pred[i]:
            if y[i] == 1.0:
                TP +=1
            else:
                TN +=1
        else:
            if y[i] == 1.0:
                FN +=1
            else:
                FP +=1
    print('Conflusion matrix:\n')
    print('      y = | 1 | 0')
    print(' '*11 + '_'*7)
    print(f'y_pred = 1| {TP} | {FP}')
    print(' '*11 + '_'*7)
    print(f'y_pred = 0| {FN} | {TN}')
    return TP, TN, FP, FN

In [88]:
TP, TN, FP, FN = c_matrix(y, y_pred)

Conflusion matrix:

      y = | 1 | 0
           _______
y_pred = 1| 5 | 0
           _______
y_pred = 0| 0 | 5


In [89]:
TP2, TN2, FP2, FN2 = c_matrix(y, y_pred_2)

Conflusion matrix:

      y = | 1 | 0
           _______
y_pred = 1| 1 | 4
           _______
y_pred = 0| 4 | 1


In [90]:
def precision(TP, FP):
    return TP / (TP + FP)

def recall(TP, FN):
    return TP / (TP + FN)
    
def f1_score (p, r):
    return 2 * p * r / (p + r)

In [92]:
p = precision(TP, FP)
r = recall(TP,FN)
f1 = f1_score(p, r)
print (f'Precision = {p}; recall = {r}; f1 score = {f1}')

Precision = 1.0; recall = 1.0; f1 score = 1.0


In [93]:
p2 = precision(TP2, FP2)
r2 = recall(TP2,FN2)
f1_2 = f1_score(p2, r2)
print (f'Precision = {p2}; recall = {r2}; f1 score = {f1_2}')

Precision = 0.2; recall = 0.2; f1 score = 0.20000000000000004


6. Могла ли модель переобучиться? Почему?

Да, могла, как и любая линейная модель при чрезмерной "подгонке" к данным при увеличении количества шагов.

7*. Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [100]:
def eval_model_l1(X, y, iterations, alpha=1e-4, lambda_ = 1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T)+ lambda_ * np.sign(W))
#         if i % (iterations / 10) == 0:
#             print(i, W, err)
    return W, err

In [101]:
min_err = np.inf
for i in iter_lst:
    for a in alpha_lst:
        W, err = eval_model_l1(X_st, y, iterations=i, alpha=a)
        print (f'iterations = {i}, alpha = {a}:\n W = {W}, logloss = {err}')
        if err < min_err  and err > 0:
            min_err = err
            alpha_best = a
            iter_best = i
            W_best = W
            print ('!!!NEW minimum!!!\n')
print(f' Best params:\n iterations = {iter_best}, alpha = {alpha_best}, logloss = {min_err}\n\
        Weights = {W_best}')
    

iterations = 10000, alpha = 0.01:
 W = [-2.51274502 -0.94368344  0.39955651  3.12663702], logloss = 0.3755487349043972
!!!NEW minimum!!!

iterations = 10000, alpha = 0.05:
 W = [-7.41718195 -1.1367363  -1.36753835  6.52352589], logloss = 0.2703273583707399
!!!NEW minimum!!!

iterations = 10000, alpha = 0.1:
 W = [-10.66480789  -1.37741394  -2.39588263   9.07005092], logloss = 0.2329250390505042
!!!NEW minimum!!!

iterations = 10000, alpha = 0.5:
 W = [-24.13442518  -2.55849245  -6.35326604  19.99384281], logloss = 0.1455176664837899
!!!NEW minimum!!!

iterations = 10000, alpha = 1:
 W = [-32.8621246   -3.34708919  -8.82685646  27.06400852], logloss = 0.11649380688157338
!!!NEW minimum!!!

iterations = 20000, alpha = 0.01:
 W = [-4.2633311  -0.98069247 -0.2696302   4.25219583], logloss = 0.32695759145278946
iterations = 20000, alpha = 0.05:
 W = [-10.66455222  -1.37739341  -2.39580382   9.06984661], logloss = 0.23292484940026456
iterations = 20000, alpha = 0.1:
 W = [-15.26118334  -1.76

In [103]:
def eval_model_l2(X, y, iterations, alpha=1e-4, lambda_=1e-6):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T) + lambda_ * W)
#         if i % (iterations / 10) == 0:
#             print(i, W, err)
    return W, err

In [104]:
min_err = np.inf
for i in iter_lst:
    for a in alpha_lst:
        W, err = eval_model_l2(X_st, y, iterations=i, alpha=a)
        print (f'iterations = {i}, alpha = {a}:\n W = {W}, logloss = {err}')
        if err < min_err  and err > 0:
            min_err = err
            alpha_best = a
            iter_best = i
            W_best = W
            print ('!!!NEW minimum!!!\n')
print(f' Best params:\n iterations = {iter_best}, alpha = {alpha_best}, logloss = {min_err}\n\
        Weights = {W_best}')
    

iterations = 10000, alpha = 0.01:
 W = [-2.51825577 -0.94523916  0.40030149  3.13235793], logloss = 0.37536207896918156
!!!NEW minimum!!!

iterations = 10000, alpha = 0.05:
 W = [-7.45293763 -1.13920006 -1.37962147  6.55105056], logloss = 0.2698316476191735
!!!NEW minimum!!!

iterations = 10000, alpha = 0.1:
 W = [-10.73937479  -1.38353948  -2.41925793   9.12993392], logloss = 0.23219527460339262
!!!NEW minimum!!!

iterations = 10000, alpha = 0.5:
 W = [-24.46930143  -2.58904324  -6.44942042  20.2662262 ], logloss = 0.14412069508071992
!!!NEW minimum!!!

iterations = 10000, alpha = 1:
 W = [-33.4501508   -3.40059937  -8.993192    27.53948077], logloss = 0.11498364023945437
!!!NEW minimum!!!

iterations = 20000, alpha = 0.01:
 W = [-4.27580423 -0.98159227 -0.27388078  4.26149241], logloss = 0.32665831155283265
iterations = 20000, alpha = 0.05:
 W = [-10.73911897  -1.38351889  -2.41917914   9.12972938], logloss = 0.23219504923406364
iterations = 20000, alpha = 0.1:
 W = [-15.41171687  -1